sofa1/config/routes.rb
Sofa1::Application.routes.draw do
  get "pages/index"
  get "pages/about_us"
  get "pages/services"
  get "pages/catalog"
  get "pages/shipping"
  get "pages/sales"
  get "pages/for_designers"
  get "pages/contacts"
  post "pages/send_feedback"#, controller: "pages", action: "send_feedback"

  get "main/about_us"

  root 'pages#index'

  get "main/index2"
  get "main/index3"

  get "images/new"
  get "images/index"
  get "images/get"
  get "images/create"
  get "images/edit"
  get "images/delete"
  get "images/refresh", controller: "images", action: "refresh"

  resources :products
  get '/products/new'
  get '/products/create'

  resources :categories
  get '/categories/new'
  get '/categories/create'

  resources :images

  get '/signup', controller: :users, action: :new
  get '/edit_profile', controller: :users, action: :edit
  get '/add_to_cart/:id', to: 'carts#add_product', as: :add_to_cart
  get '/remove_from_cart/:id', to: 'carts#remove_product', as: :remove_from_cart
  get '/remove_line_from_cart/:id', to: 'carts#remove_line', as: :remove_line_from_cart
  get '/refresh_cart', to: 'carts#refresh', as: :refresh_cart, defaults: {format: :js}
  resources :users, except: [:new, :edit, :add_to_cart]

  get '/my_cart', controller: :carts, action: :show, as: :my_cart

  get '/login', controller: :users, action: :login

  get '/nimda', controller: :admin, action: :authenticate
  get '/logout', controller: :admin, action: :logout

  get '/signin', controller: :sessions, action: :new
  post '/signin', controller: :sessions, action: :create
  get '/signout', controller: :sessions, action: :destroy

  

end

sofa1/app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :presence => true
  validates :description, :presence => true


  has_and_belongs_to_many :categories

  has_many :product_images, class_name: "ProductImage"
  has_many :images, through: :product_images

  has_many :positions
  has_many :carts, through: :positions

  def main_image
    return product_images.order(:priority).first.image
  end

  def add_image image, position
    if product_images.include? image
      im = product_images.where(image_id: image.id).first
      im.priority = position
    else
      product_images.create image: image, priority: position
    end
  end

  # кажется, не используется
  def roubles (sum = price, options: :nominative)
    splitted = sum.to_s.split ""
    if options == :nominative then
      if (10..20).include?(splitted.last(2).join.to_i) or (5..9).include?(splitted.last.to_i) or splitted.last.to_i == 0
        "рублей"
      elsif splitted.last.to_i == 1
        "рубль"
      elsif (2..4).include? splitted.last.to_i
        "рубля"
      end
    elsif options == :genitive
      if splitted.last.to_i == 1
        "рубля"
      else
        "рублей"
      end
    end

  end

end

sofa1/app/controllers/products_controller.rb
  class ProductsController < ApplicationController

  # /products GET
  before_filter :del_empty_categories, only:[:create, :update]
  skip_before_filter :verify_authenticity_token, only: [:destroy]
  #http_basic_authenticate_with name: login, password: password, except: [:index, :show]
  before_action :is_admin?, only: [:new, :edit, :create]

  def index
    @products = Product.all
    @positions = ProductImage.all
  end

  # /product/1 GET

  def show
    @params = params
    @product = Product.find(params[:id])
    @price = @product.price

    respond_to do |format|
      format.html
      #format.js {render template: 'layouts/show'}

    end
  end

  # /product/new GET
  def new
    @categories = Category.all
    @product = Product.new
    @products = Product.all
    @image = Image.new
    @images = Image.all
  end

  # /products/1/edit GET
  def edit
    @product = Product.find(params[:id])
    @categories = Category.all
    @images = Image.all
    @maximal_priority = @product.product_images.order(:priority).first
    @positions = ProductImage.all

  end

  # /products POST
  def create
    #TODO: Добавление фото
    @product = Product.new(product_params)
    @categories = Category.find( params[:product][:category_ids] )
    @product.categories = @categories
    @images = Image.find(params[:image_checked].keys)
    checked = params[:image_checked].keys
    checked.each { |i|
      im = Image.where(id: i).first
      @position = ProductImage.new product: @product, image: im, priority: params[:image_priority][i]
      @position.save
    }

    redirect_to :products
  end

  # /products/1 PUT
  def update
    @product = Product.includes(:product_images).includes(:images).find (params[:id])
    @categories = Category.find( params[:product][:category_ids] )
    @product.categories = @categories
    #@product.main_image_id = params['main_image']
    @images = Image.find(params[:image_checked].keys.to_a)
    @product.images = @images
    checked = params[:image_checked].keys
    checked.each {|i|
      pr_img = @product.product_images.find_by image_id: i
      ProductImage.update pr_img, priority: params[:image_priority][i]
    }
    @product.update (product_params)
    @product.save
    redirect_to :edit_product
  end

  # /products/1 DELETE
  def destroy
    @product = Product.find(params[:id])
    @product.delete
    redirect_to :products
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :sizes, :category_ids, :price)
  end

  def del_empty_categories
    params[:product][:category_ids].delete("")
  end

end

sofa1/app/helpers/products_helper.rb
module ProductsHelper
end

sofa1/app/views/products/create.html.slim
div :style = 'margin:0 0 0 50px'
= @product
= form_for @product do |f|
  = f.label :name, 'Название'
  br
  = f.text_field :name, style: 'width:300px;'
  br
  = f.label :name, 'Описание'
  br
  = f.text_area :description, style: 'width:300px;'
  br
  = f.submit
= products_path
br
= products_path.class.name
br
= products_path.class.superclass.name
br
/= product_path
/= @product
/- @product.name = 'dckwhkch'

sofa1/app/views/products/edit.html.slim
= stylesheet_link_tag "product"
/= javascript_include_tag "tinymce/tinymce.min.js"
/= javascript_include_tag "tinymce_start"
= stylesheet_link_tag "css/jquery.cleditor.css"
/= stylesheet_path "//javascripts/CLEditor/jquery.cleditor.css"
/= stylesheet_link_tag "/assets/javascripts/CLEditor/jquery.cleditor.css"
= javascript_include_tag "CLEditor/jquery.cleditor.js"
= javascript_include_tag "CLEditor/jquery.cleditor.min.js"
= javascript_include_tag "CLEditor_start.js"
/script type = "text/javascript"
/  | tinymce.init({selector: "textarea", width:600});
.container
  h1 Изменение продукта
  = form_for @product do |f|
    .category_elements
      = f.collection_check_boxes :category_ids, @categories, :id, :name  do |cb|
        p
          = cb.label { cb.check_box + cb.text}
    = f.label "Название"
    br
    = f.text_field :name, style: "width: 300px"
    br
    = f.label "Описание товара"
    br
    = f.text_area :description, style: "width: 500px"
    br
    = f.label "Размеры товара"
    br
    = f.text_area :sizes, style: "width: 500px"
    br
    = f.text_field :price
    br
    = f.submit "Сохранить изменения"
    br
    br
    - @images.each do |i|
      /- if i.priority == 1
      - if @product.product_images.where(image_id: i.id).first
        - puts "Testing iterating: "
        - puts i.id
        - if @maximal_priority.image_id == i.id
          .contains_main_image
            = image_tag i.file_path, style: "height: 100px"
            br
            label
              = check_box_tag "image_checked[#{i.id}]", 1, true
              | Добавить фото
            br
            label
              | Приоритет фото (ниже значение — выше приоритет)
              br
              = number_field_tag "image_priority[#{i.id}]", i.get_priority
            br
        - elsif @product.image_ids.include? i.id
          .contains_not_main_image
            = image_tag i.file_path, style: "height: 100px"
            br
            label
              = check_box_tag "image_checked[#{i.id}]", 1, true
              | Добавить фото
            br
            label
              | Приоритет фото (ниже значение — выше приоритет)
              br
              = number_field_tag "image_priority[#{i.id}]", i.get_priority
            br
      - else
        .contains_other_image
          = image_tag i.file_path, style: "height: 100px"
          br
          label
            = check_box_tag "image_checked[#{i.id}]", 1, false
            | Добавить фото
          br
          label
            | Приоритет фото (ниже значение — выше приоритет)
            br
            = number_field_tag "image_priority[#{i.id}]", 5
          br

sofa1/app/views/products/index.html.slim
= stylesheet_link_tag "product"

.container style = 'width:850px'
  .leftblock
    - @products.each do |p|
      .product
        = link_to product_path p.id
          /- if (img_path = p.images.order(:priority).first.file_path)
          /- if @positions.products.includes(p)
          - if product_image = @positions.where(product_id: p.id).order(:priority).first
            - if (img_path = product_image.image.file_path)
              = image_tag img_path
          - else
            = image_tag "sofas/imgs/noimage.png"
              /= print image_tag "sofas/imgs/g  noimage.png"
          /= image_tag  (p.images.find_by(id: 1).file_path : "noimage.png").to_s, :class => '300px'
        .info
          p.name
            == p.name
          p.description
            == (HTMLEntities.new.decode(strip_tags p.description)).split(" ").first(25).join " "
            = "..."
            = link_to " далее", product_path(p), class: "next"
            br
            p.price
              - if p.price == 0
                = "Нет цены"
              - else
                = "от "
                span.value
                  = p.price.to_s + " "
                = roubles p.price, options: :genitive
          - if admin?
            .admin_edit
              = link_to 'удалить продукт', p, :method => :delete, action: :destroy, data: {:confirm => 'Вы хотите удалить продукт?'}
              br
              = link_to 'редактировать продукт', edit_product_path(p.id), action: :edit, data: {:confirm => 'Вы переходите на страницу редактирования. Продолжить?'}
    br
    br
    - if admin?
      = link_to "Вернуться к добавлению продуктов", :products_new

  = render "layouts/rightblock"

sofa1/app/views/products/new.html.slim
/= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"
= stylesheet_link_tag "product"

= stylesheet_link_tag "css/jquery.cleditor.css"

= javascript_include_tag "CLEditor/jquery.cleditor.js"
= javascript_include_tag "CLEditor/jquery.cleditor.min.js"
= javascript_include_tag "CLEditor_start.js"

/style p, h1 {margin-left:50px;};

.container
    h1 Добавление продуктов
    = form_for @product do |f|
        .category_elements
            = f.collection_check_boxes :category_ids, @categories, :id, :name  do |cb|
                p
                    = cb.label { cb.check_box + cb.text}
        p style = 'float:left;'
        = f.label 'Название'
        br
        = f.text_field :name, {style:'width:300px'}
        br
        = f.label 'Описание'
        br
        = f.text_area :description, {style:'width:500px;height:400px;'}
        br
        = f.label 'Размеры'
        br
        = f.text_area :sizes, {style:'width:500px;height:400px;'}
        br
        = f.label "Цена (в рублях)"
        br
        = f.text_field :price
        br
        = f.submit 'Создать продукт'
        br
        br

        - @images.each do |i|
            .contains_other_image
                = image_tag i.file_path, style: 'height: 100px;'
                br
                label
                    = check_box_tag "image_checked[#{i.id}]"
                    | Добавить фото
                br
                label
                    = radio_button_tag :main_image, i.id
                    | Сделать главным
                br
                label
                    = number_field_tag "image_priority[#{i.id}]", 5

sofa1/app/views/products/show.html.slim
/- @product.images.each do |i|
/  = image_tag "sofas/imgs/" + i.file_path, :class => '300px'
/  br

= stylesheet_link_tag "product"
/= stylesheet_link_tag "css/mainstyles"
= stylesheet_link_tag "css/productstyles"
= stylesheet_link_tag "css/viewed"
= javascript_include_tag "tabs"

script type = "text/javascript"
  | window.onload = function() {
  | init_tabs(); }

.container
  .productleft
    = link_to "Главная >", :root, class: "path"
    = link_to "Каталог >", :products, class: "path"
    = link_to @product.name, :product, class: "path last"
    p.productname #{@product.name}
    = link_to "Нет отзывов. Нужна таблица", :product, class: "reviewsnumber"
    p.description #{(HTMLEntities.new.decode(strip_tags @product.description)).split(" ").first(45).join " "}
    .priceblock
      - if @product.price
        p.price
          = @product.price
          = " "
          = roubles @product.price
      - else
        p.price Нет цены

      = link_to add_to_cart_path(@product.id), remote: true
        = image_tag "addtocart.png", class: "addtocart", alt: "Добавить в корзину"
    = image_tag "", class: "chosenfabric"
  .productright
    = image_tag @product.main_image.file_path
    br
    div
      - @product.images.each do |i|
        = link_to i.file_path
          = image_tag i.file_path

  .tab_module
    ul
      li onclick = "on_click_handler(this, 'description')"
        | описание
      li onclick = "on_click_handler(this, 'sizes')"
        | размеры
      li onclick = "on_click_handler(this, 'choose_fabric')" class="last"
        | ткани
    .tab_content_box
      #description.tab_content
        .product_descr_text
          == @product.description
      #sizes.tab_content
        p
          == @product.sizes
      #choose_fabric.tab_content
        p.product_descr_header
        .fabric_cat
          /TODO Сделать и заполнить таблицу тканей. Отобразить здесь. Ткань: id, name, description
          = image_tag "fabrics/mini/2_1_2_002.jpg", onclick: "on_fabric_click(this)"
          = image_tag "fabrics/mini/38_002.jpg", onclick: "on_fabric_click(this)"
          = image_tag "fabrics/mini/almond.jpg", onclick: "on_fabric_click(this)"
          = image_tag "fabrics/mini/almond_002.jpg", onclick: "on_fabric_click(this)"
          = image_tag "fabrics/mini/ash.jpg", onclick: "on_fabric_click(this)"