sofa1/config/routes.rb
Sofa1::Application.routes.draw do
  get "pages/index"
  get "pages/about_us"
  get "pages/services"
  get "pages/catalog"
  get "pages/shipping"
  get "pages/sales"
  get "pages/for_designers"
  get "pages/contacts"
  post "pages/send_feedback"#, controller: "pages", action: "send_feedback"

  get "main/about_us"

  root 'pages#index'

  get "main/index2"
  get "main/index3"

  get "images/new"
  get "images/index"
  get "images/get"
  get "images/create"
  get "images/edit"
  get "images/delete"
  get "images/refresh", controller: "images", action: "refresh"

  resources :products
  get '/products/new'
  get '/products/create'

  resources :categories
  get '/categories/new'
  get '/categories/create'

  resources :images

  get '/signup', controller: :users, action: :new
  get '/edit_profile', controller: :users, action: :edit
  get '/add_to_cart/:id', to: 'carts#add_product', as: :add_to_cart
  get '/remove_from_cart/:id', to: 'carts#remove_product', as: :remove_from_cart
  get '/remove_line_from_cart/:id', to: 'carts#remove_line', as: :remove_line_from_cart
  get '/refresh_cart', to: 'carts#refresh', as: :refresh_cart, defaults: {format: :js}
  resources :users, except: [:new, :edit, :add_to_cart]

  get '/my_cart', controller: :carts, action: :show, as: :my_cart

  get '/login', controller: :users, action: :login

  get '/nimda', controller: :admin, action: :authenticate
  get '/logout', controller: :admin, action: :logout

  get '/signin', controller: :sessions, action: :new
  post '/signin', controller: :sessions, action: :create
  get '/signout', controller: :sessions, action: :destroy

  

end

sofa1/app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :positions
  has_many :products, through: :positions

  def add_product product
    if products.include? product
      positions.where(product_id: product.id).first.increment! :quantity
    else
      positions.create product: product, quantity: 1
    end
  end

  def remove_product product
    if position = positions.find_by(product_id: product.id)
      if position.quantity == 0
        position.delete
      else
        position.decrement :quantity
        position.save
      end
      true
    else
      false
    end
  end

  def sum
    @sum = 0
    positions.map {|i| @sum += i.product.price * i.quantity}
    return @sum
  end
end

sofa1/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    #if session[:user]
    #  user = User.includes(:cart).find session[:user]
    #  @positions = user.cart.positions
    #elsif session[:cart]
    #
    #end
    @items = get_cart_items
    @cart_sum  = 0
    if @items.any?
      @items.each {|i|
      @cart_sum += i[:quantity] * i[:price]
      }
    end
    #respond_to {|format|
    #  #format.js { render partial: 'carts/show.js.erb', locals: {js: true}}
    #  format.html { render 'show', locals: {js: true}}
    #}
    ##render template: 'carts/_show.js.erb', locals: {js: true}
  end
  def add_product
    if session[:user]
      if user = User.find(session[:user])
        user.add_to_cart params[:id]
        #respond_to {|format|
        #  format.html { render controller: :products, action: :show, id: params[:id]}
        #}
        #render 'carts/total_price', locals: {total_sum: user.cart.sum}
      else
        flash[:notice] = 'Нет такого пользователя'
        render file: 'users/user_error'
      end
    else
      #session[:cart] = {product_id: params[:id], if session[:cart][:quantity] then session[:cart][:quantity]++ else quantity: 1}
      if session[:cart].blank?
        session[:cart] = {params[:id].to_i => 1}
      else
        if session[:cart][params[:id].to_i]
          session[:cart][params[:id].to_i] = session[:cart][params[:id].to_i] + 1
        else
          session[:cart][params[:id].to_i] = 1
        end
      end
    end
    @items = get_cart_items
    render :refresh
  end


  def remove_product
    if user = current_user
      user.remove_from_cart params[:id]
    elsif session[:cart]
      if session[:cart][params[:id].to_i] && session[:cart][params[:id].to_i] > 0
        session[:cart][params[:id].to_i] = session[:cart][params[:id].to_i] - 1
      elsif session[:cart][params[:id].to_i] &&  session[:cart][params[:id].to_i] == 0
        session[:cart].delete params[:id].to_i
      end
    end
    #respond_to {|format|
    #  format.js { render template: 'carts/refresh'}
    #  format.html {render :show}
    #}
    @items = get_cart_items
    render :refresh
  end

  def remove_line
    if session[:user] && (user = User.includes(cart: :positions).where(id: session[:user]).first)
      user.cart.positions.where(product_id: params[:id]).first.delete
    elsif session[:cart]
      if session[:cart][params[:id].to_i]
        session[:cart].delete params[:id].to_i
      end
    end
    @items = get_cart_items
    render :refresh
  end

  def refresh
    render partial: "carts/total_price", locals: {total_sum: 500}
  end

  #def get_cart_items
  #  items = []
  #  if user = current_user
  #    user.cart.positions.each {|i|
  #      items << {id: i.product_id,
  #                name: i.product.name,
  #                quantity: i.quantity,
  #                price: i.product.price}
  #    }
  #    return items
  #  elsif session[:cart]
  #    #positions = Position.includes(:product).where product_id: session[:cart].keys
  #    products = Product.where id: session[:cart].keys
  #    session[:cart].each_pair {|key, value|
  #      product = products.find_by(id: key)
  #      items << {id: key,
  #                name: product.name,
  #                quantity: session[:cart][key],
  #                price: product.price}
  #    }
  #    return items
  #  end
  #end
end

sofa1/app/helpers/carts_helper.rb
module CartsHelper
end

sofa1/app/views/carts/_cart_items.html.slim
- @items.each do |item|
  .table_row
    .table_cell = link_to 'X', remove_line_from_cart_path(item[:id]), remote: true
    .table_cell = item[:name]
    .table_cell = "нет ткани"
    .table_cell = "нет цвета"
    .table_cell
      = link_to '—', remove_from_cart_path(item[:id]), style: 'float:left;margin-left:0px;', remote: true
      span = item[:quantity]
      = link_to '+', add_to_cart_path(item[:id]), style: 'margin-left:5px', remote: true

    .table_cell = item[:price]
    .table_cell = item[:price].to_i * item[:quantity].to_i

sofa1/app/views/carts/_show.js.erb
alert('РАБОТАЕТ БЛЕАТЬ!')

sofa1/app/views/carts/_total_price.js.erb
$('#total_price').html("<%= if total_price then total_price else 0 end %>")

sofa1/app/views/carts/refresh.js.erb
$('#total_price').html("<%= total_price%>");
if ($('.table').length > 0) {
    $('.table_row').remove();
    $('.table').append("<%= escape_javascript(render partial: 'carts/cart_items')%>");
    $('.sum').html("<%= total_price%>");
    $('#roubles').html("<%= escape_javascript(' ' + roubles(total_price)) %>");
}

sofa1/app/views/carts/show.html.slim
= stylesheet_link_tag "css/basketstyles"

.container
  = link_to 'главная >', :root, class: 'path'
  = link_to 'корзина', :my_cart, class: 'path last'
  p.your_basket = 'Ваша корзина'
  .table
    .table_header
      .table_cell = 'удалить'
      .table_cell = 'наименование'
      .table_cell = 'ткань'
      .table_cell = 'цвет'
      .table_cell = 'количество'
      .table_cell = 'цена'
      .table_cell = 'сумма'
    - if @items.any?
      = render 'carts/cart_items'
    - else
      h3 корзина пока пуста
  = link_to 'обновить корзину (не реал.)', :root, class: 'refresh_basket'
  .total
    p итого:
    p.sum = total_price
    p#roubles = ' ' + roubles(total_price)
    /- if @cart_sum
    /  p.sum = @cart_sum
    /  p = ' ' + roubles(@cart_sum)
    /-else
    /  p.sum Нет данных
  - if request.headers['HTTP_REFERER']
    = link_to 'продолжить покупки', request.headers['HTTP_REFERER'],  class: 'continue'
  - else
    = link_to 'продолжить покупки', :products, class: 'continue'
  = link_to :root, class: 'make_order'
    = image_tag 'basket/make_order2.png', alt: 'оформить заказ'



/- @positions.each do |position|
/- if @positions
/  = render @positions
/- else
/  h1 still empty